queue:
  name: Hosted Ubuntu 1604
  timeoutInMinutes: 6000

trigger:
  batch: true
  branches:
    include:
    - master

variables:
  python.version: '3.7'

steps:

- task: UsePythonVersion@0
  displayName: 'Use Python $(python.version)'
  inputs:
    versionSpec: '$(python.version)'

- script: 'azure/install_dependencies.sh && pip install nose coverage twine'
  displayName: 'Install dependencies'

# - script: 'python setup.py nosetests'
#   displayName: Unit tests

- script: 'python setup.py dist && twine upload --repository-url https://test.pypi.org/legacy/ -u $(pypi_username) -p $(pypi_password) dist/*'
  displayName: PYPI deploy
