queue:
  name: Hosted Ubuntu 1604
  timeoutInMinutes: 300

trigger:
  batch: true
  branches:
    include:
    - master

variables:
  python.version: '3.7'

steps:

- task: UsePythonVersion@0
  displayName: 'Use Python $(python.version)'
  inputs:
    versionSpec: '$(python.version)'

- script: 'azure/install_dependencies.sh && pip install h5py .'
  displayName: 'Install dependencies'

- script: './download.sh'
  displayName: 'Download data files'

- script: 'python -m torchani.data.cache_aev tmp dataset/ani1-up_to_gdb4/ani_gdb_s01.h5 256'
  displayName: Cache AEV

- script: 'pip install pytorch-ignite-nightly'
  displayName: 'Install more dependencies'

- script: 'python -m torchani.neurochem.trainer --tqdm tests/test_data/inputtrain.ipt  dataset/ani1-up_to_gdb4/ani_gdb_s01.h5 dataset/ani1-up_to_gdb4/ani_gdb_s01.h5'
  displayName: NeuroChem Trainer

- script: 'python -m torchani.neurochem.trainer --tqdm tests/test_data/inputtrain.yaml  dataset/ani1-up_to_gdb4/ani_gdb_s01.h5 dataset/ani1-up_to_gdb4/ani_gdb_s01.h5'
  displayName: NeuroChem Trainer YAML config
