package:
  name: torchani
  version: {{ GIT_DESCRIBE_TAG }}.{{ GIT_BUILD_STR }}

source:
  # git_url only captures committed code
  git_url: ../

build:
  number: 0
  string: py{{ python }}_torch{{ pytorch }}_cuda{{ cuda }}
  script: "CUDA_HOME=/usr/local/cuda {{ PYTHON }} -m pip install --config-settings=--global-option=ext-all-sms --no-build-isolation -v ."
  entry_points:
    - ani = torchani.cli:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # For source.git_url
    - conda-forge::git
  host:
    - conda-forge::python={{ python }}
    - conda-forge::typing_extensions>=4.0.0
    - conda-forge::pip
    - conda-forge::setuptools>=64
    - conda-forge::setuptools_scm>=8
    - pytorch::pytorch={{ pytorch }}
    - pytorch::pytorch-cuda={{ cuda }}
    - conda-forge::numpy=1.26
  run:
    - conda-forge::python={{ python }}
    - conda-forge::typing_extensions>=4.0.0
    - conda-forge::numpy=1.26
    - conda-forge::h5py
    - conda-forge::tqdm
    - conda-forge::rich
    - conda-forge::typer
    - pytorch::pytorch={{ pytorch }}
    - pytorch::pytorch-cuda={{ cuda }}

test:
  imports:
    - torchani

about:
  home: https://roitberg.chem.ufl.edu
  license: MIT
  license_file: LICENSE
  summary: Roiberg Group Sandbox
