# Configuration file that stores all hooks that pre-commit runs
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: no-commit-to-branch  # disallow commiting to master / main directly
        args: ['--branch', 'main', '--branch', 'master']
        stages: [pre-commit]
      - id: check-yaml  # check yaml files for parsable syntax
        stages: [pre-push]
      - id: check-toml  # checks toml files for parsable syntax
        stages: [pre-push]
      - id: check-json  # checks json files for parsable syntax
        stages: [pre-push]
      - id: check-added-large-files  # prevent large files from commit
        stages: [pre-push]
      - id: check-merge-conflict  # checks for merge conflict strings
        stages: [pre-push]
      - id: debug-statements  # checks for "breakpoint()" and debugger imports
        stages: [pre-push]

  - repo: local
    hooks:
      - id: builtin-datasets-codegen
        name: builtin-datasets-codegen
        entry: "python ./tools/builtin-datasets-codegen.py"
        # Don't generate a venv for the exe
        language: system
        types: [python]
        # Pass no files but run regardless
        files: $^
        always_run: true
        # Print output on success
        verbose: true
        stages: [pre-push]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        stages: [pre-push]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        stages: [pre-push]

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: "mypy --ignore-missing . --exclude='(build/.*|tests/.*|tools/.*|docs/src/examples_autogen/.*|docs/build/.*)'"
        # Don't generate a venv for the exe
        language: system
        types: [python]
        # Pass no files but run regardless
        files: $^
        always_run: true
        # Print output on success
        verbose: true
        stages: [pre-push]
