name: ani
channels:
  - nodefaults
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/nvidia
dependencies:
  # General
  - python=3.10
  - pip

  # Required dependencies:
  - numpy>=1.24
  - pytorch=2.3
  - pytorch-cuda=11.8
  - typing_extensions>=4.0.0
  - h5py  # HDF5 backend for datasets
  - tqdm  # progress bar util
  - lark-parser  # legacy neurochem files

  # For building the extensions, the cuda libraries speciefied by the pytorch-cuda
  # metapackage are not enough, so we use the nvidia::cuda-toolkit=11.8 metapackage
  # to fetch missing libraries. The issue is that nvidia bundles nvcc-12.4, so we
  # specifically override it with nvidia::cuda-nvcc-11.8, since pytorch errors out
  # on 12.4
  # TODO: Fix this
  - nvidia::cuda-toolkit=11.8
  - nvidia::cuda-nvcc=11.8

  # Other optional dependencies follow:
  # Ase interface, needed for dynamics and for tests/tools/docs:
  - ase

  # Tests:
  - coverage  # code coverage
  - black  # formatter
  - flake8  # linter
  - mypy  # type checking
  - pytest  # tests runner
  - parameterized  # parametrize test classes
  - hypothesis  # indirect dependency of torch.testing
  - expecttest  # indirect dependency of torch.testing
  # Extra data backends for tests:
  - pandas  # Parquet backend
  - pyarrow  # Parquet backend
  - zarr  # Zarr backend

  # Tools :
  - matplotlib
  - pynvml

  # Docs:
  - sphinx
  - sphinx_rtd_theme
  - sphinx-gallery
  - tensorboard
