name: ani
channels:
  - nodefaults
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/nvidia
dependencies:
  # general
  - python=3.8.1
  - pip

  # Data
  - h5py  # HDF5 backend

  # DL
  - numpy=1.20
  - pytorch=1.13.1
  - cudatoolkit=11.6

  # Progress bars
  - tqdm
  - pkbar

  # Legacy neurochem parser
  - lark-parser
  - pyyaml
  - requests

  # Ase interface
  - ase
