name: ani-dev
channels:
  - nodefaults
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/nvidia
dependencies:
  # General
  - python=3.8.1
  - pip

  # Core
  - numpy=1.20
  - mkl=2024.0.0
  - pytorch=1.13.1
  - cudatoolkit=11.6

  # Data
  - h5py  # HDF5 backend
  - pyyaml  # builtin datasets specification

  # Utils
  - tqdm  # progress bar

  # Ase interface
  - ase

  # Neurochem files (legacy)
  - lark-parser
  - requests

  # Linters / checkers / tests / CI
  - black
  - flake8
  - mypy
  - coverage
  - pytest
  - parameterized
  - expecttest

  # Docs and tools
  - sphinx
  - sphinx_rtd_theme
  - sphinx-gallery
  - matplotlib
  - pillow
  - pynvml

  # Extra data backends
  - pandas  # csv support
  - pyarrow  # Parquet backend
  - zarr  # Zarr backend
