name: conda

# This workflow runs
# - on pull_requests that contain the word 'conda' in the branch name
# - on the default branch, at 00:00:00 every day
on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

env:
  TAG: torchani-nightly/conda-pkg:${{ github.sha }}

jobs:
  build-pkg:
    if: ${{ contains(github.head_ref, 'conda') || github.event_name == 'schedule' }}
    runs-on: [self-hosted, ipickering]
    permissions:
      contents: read

    steps:
      - name: Build conda pkg in Docker image, release if needed
        uses: docker/build-push-action@v5
        with:
          tags: ${{ env.TAG }}
          build-args: |
            INTERNAL_RELEASE=${{ contains(github.head_ref, 'release') || github.event_name == 'schedule' }}
            PUBLIC_RELEASE=0
          file: conda.Dockerfile
          shm-size: 1g
          ulimit: |
            memlock=-1
            stack=67108864
          # DOCKER_PVTKEY is needed to upload to internal server
          # CONDA_TOKEN is needed to upload to anaconda.org
          secrets: |
            "DOCKER_PVTKEY=${{ secrets.DOCKER_PVTKEY }}"
            "CONDA_TOKEN=${{ secrets.CONDA_TOKEN }}"
        continue-on-error: true

      - name: Remove image
        if: ${{ always() }}
        run: docker image rm --force ${{ env.TAG }}

concurrency:
  group: conda-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
