name: conda

# This workflow runs
# - on pull_requests that contain the word 'conda' in the branch name
# - on the default branch, at 00:00:00 every day
on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-pkg:
    if: ${{ contains(github.head_ref, 'conda') || github.event_name == 'schedule' }}
    runs-on: [self-hosted, ipickering]
    permissions:
      contents: read

    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}/conda-pkg

      - name: Build conda pkg in Docker image, release if needed
        uses: docker/build-push-action@v5
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            INTERNAL_RELEASE=${{ contains(github.head_ref, 'release') || github.event_name == 'schedule' }}
            PUBLIC_RELEASE=0
          file: conda.Dockerfile
          shm-size: 2g
          ulimit: |
            memlock=-1
            stack=67108864
          # DOCKER_PVTKEY is needed to upload to internal server
          # CONDA_TOKEN is needed to upload to anaconda.org
          secrets: |
            "DOCKER_PVTKEY=${{ secrets.DOCKER_PVTKEY }}"
            "CONDA_TOKEN=${{ secrets.CONDA_TOKEN }}"

      - name: Remove image
        if: ${{ always() }}
        continue-on-error: true
        run: docker image rm ${{ steps.meta.outputs.tags }}

concurrency:
  group: conda-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
