name: docs

on: pull_request

jobs:
  docs:
    runs-on: [self-hosted, ipickering]
    permissions:
      contents: read

    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}/docs

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1

      - name: Build extensions and run tests
        run: >-
          docker run
          --rm
          --gpus '"device=none"'
          ${{ steps.meta.outputs.tags }}
          bash -c
          "sphinx-build -W docs/src docs/build"

      - name: Remove image
        if: ${{ always() }}
        continue-on-error: true
        run: docker image rm ${{ steps.meta.outputs.tags }}

concurrency:
  group: docs-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
