name: stable-torch-1.9.1

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  stable-torch:

    runs-on: self-hosted
    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Fetch submodules
      run: git submodule update --init
    - name: Install cuda
      run: |
        source ci/install_cuda.sh
        echo "CUDA_HOME=${CUDA_HOME}" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
        echo "PATH=${CUDA_HOME}/bin:$PATH" >> $GITHUB_ENV
    - name: Install dependencies
      run: ci/install_stable_dependencies.sh
    - name: Pytorch info
      run: python -c 'from torch.utils.collect_env import get_pretty_env_info; print(get_pretty_env_info())'
    - name: Install TorchANI
      run: |
        echo $CUDA_HOME
        echo $LD_LIBRARY_PATH
        nvcc -V
        python setup.py install --ext --only-sm80
    - name: Download data files
      run: ./download.sh
    - name: install pytest
      run: pip install pytest
    - name: Run all tests
      run: cd tests; python -m pytest -v -s *.py  # import torchani in root dir will not import the compiled one

concurrency:
  group: stable-torch
  cancel-in-progress: true