name: unittests

on: pull_request

env:
  REGISTRY: ${{ github.repository }}
  IMAGE_NAME: 'unittests-ext'

jobs:
  cpu-tests:
    runs-on: [self-hosted, ipickering]
    permissions:
      contents: read

    steps:
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run unit tests (CPU)
        run: >-
          docker run
          --rm
          --gpus '"device=none"'
          ${{ steps.meta.outputs.tags }}
          bash -c "pytest ."

      - name: Remove image
        if: ${{ always() }}
        continue-on-error: true
        run: docker image rm ${{ steps.meta.outputs.tags }}

concurrency:
  group: unittests-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
